### ISSUE TITLE
Breaking changes in API between 0.5.0 and 0.5.1

### ISSUE THREAD

**Issue by wksinha** [Embers-of-the-Fire/rust-table-formatter#11]
There are breaking changes between versions 0.5.0 and 0.5.1, for instance:
in cell.rs
    formatter: Vec<fn(ColoredString) -> ColoredString>,
changes to
    formatter: Vec\<FormatterFunc\>,
Reference:
https://github.com/Embers-of-the-Fire/rust-table-formatter/commit/658b7a37235ffbacfe93dc84900d43a9cd34344a

Programs (for example- https://github.com/XAMPPRocky/tokei) relying on the library end up failing (https://github.com/XAMPPRocky/tokei/issues/1011) because of this, as cargo treats dependencies of the form "x.y.z" as "^x.y.z", i.e., specifying version 0.5.0 as a dependency allows cargo to use 0.5.1 as a drop-in replacement.

**Comment by Embers-of-the-Fire** [comment]
Oh, sorry, my bad. I've forgotten that change. I'll yank 0.5.1 and republish it as a breaking version.

**Comment by wksinha** [comment]
Thank you for the fix, really appreciate the help!
